spring:
  application:
    name: ASM_JAVA5

  datasource:
    url: jdbc:sqlserver://localhost:1433;database=FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

logging:
  level:
    org:
      hibernate:
        sql: debug
      springframework:
        security: debug

app:
  admin:
    username: ADMIN
    password: ADMIN
